# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [6]:
def share_bread(N, K):
    x = K // N # Количество кусков, которое достанется каждому хоббиту
    y = K % N # Остаток кусков, который остается у Сэма
    return x, y

# Пример
assert share_bread(N=3, K=14) == (4, 2)
print (share_bread(N=3, K=14))

(4, 2)


## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [2]:
def leap_year(year):
    if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
        return "YOU SHALL PASS"
    else:
        return "YOU SHALL NOT PASS"

assert leap_year(5) == 'YOU SHALL NOT PASS'
print (leap_year(400))

YOU SHALL PASS


## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [16]:
import math
def amulet_area(a, b, c):
    if a + b <= c or a + c <= b or b + c <= a:
        return "Треугольник с такими сторонами не существует!"
    # Полупериметр
    p = (a + b + c) / 2
    # Площадь по формуле Герона
    S = math.sqrt(p * (p - a) * (p - b) * (p - c))
    return S

assert amulet_area(3, 4, 5) == 6
print (amulet_area(1, 2, 5))

Треугольник с такими сторонами не существует


## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [2]:
import numpy as np

def cal_euclidean(a, b):
    """
    Вычисляет евклидово расстояние между векторами a и b.
    Формула: sqrt(sum((a - b)^2))
    """
    distance = np.sqrt(np.sum((a - b) ** 2))
    return distance

def cal_manhattan(a, b):
    """
    Вычисляет манхэттенское расстояние между векторами a и b.
    Формула: sum(|a - b|)
    """
    distance = np.sum(np.abs(a - b))
    return distance

def cal_cosine(a, b):
    """
    Вычисляет косинусное расстояние между векторами a и b.
    Косинусное расстояние = 1 - (a · b / (||a|| * ||b||))
    """
    distance = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
    return distance


In [3]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

26.19160170741759
66
-0.008964214570007952


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [4]:
my_array = np.random.rand(100)
my_array = (my_array - np.min(my_array)) / (np.max(my_array) - np.min(my_array))

print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.09013373 0.24712086 0.52282256 0.74749042 0.17380278 0.46981252
 0.15721918 0.00222067 0.24787089 0.74194511 0.44974273 0.22087507
 0.57236627 0.4966815  0.44720026 0.99920488 0.55473146 0.70942139
 0.32474527 0.48383155 0.38675232 0.23037549 0.4235361  1.
 0.37350084 0.16251978 0.00925541 0.88803377 0.53781248 0.57607512
 0.69581286 0.11567231 0.50145363 0.12758231 0.26327431 0.43071062
 0.98625277 0.94273309 0.31211524 0.01876687 0.77159499 0.46539282
 0.6217443  0.         0.23926115 0.53976459 0.1788603  0.68478756
 0.0416961  0.65246929 0.08505032 0.71480762 0.69414893 0.4610684
 0.22119635 0.43897532 0.52029461 0.37797163 0.06319922 0.17146914
 0.3137347  0.88241369 0.23212323 0.19523934 0.39251429 0.93465429
 0.80488485 0.3187367  0.6554111  0.79349167 0.26104855 0.18661053
 0.92846815 0.15690581 0.76922472 0.46927452 0.40637739 0.72803684
 0.50989806 0.48707674 0.20677274 0.20262764 0.81154241 0.93483456
 0.54049549 0.73297116 0.96712773 0.50111887 0.65981921 0.35691

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [5]:
# Создание матрицы 5x6 с целыми числами в интервале [0,50]
my_array = np.random.randint(0, 51, size=(5, 6))
# Поиск максимального элемента и его колонки
max_element = np.max(my_array)
col_index = np.where(my_array == max_element)[1][0]
selected_column = my_array[:, col_index]

print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[ 9  8  4 24 39  3]
 [16  4 30 50  0 33]
 [ 9 45 31 25 31 28]
 [ 6 40 43 41  3 19]
 [29 15 36 36 49 11]]
[24 50 25 41 36]


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [25]:
def get_unique_rows(X):
    """
    Принимает на вход матрицу X и возвращает новую матрицу, 
    содержащую только уникальные строки из X.
    """
    X_unique = np.unique(X, axis=0)  # Удаляем дубликаты строк
    return X_unique

In [27]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 5 5]
 [5 4 5]
 [5 4 4]
 [4 4 5]
 [5 4 4]
 [5 4 5]
 [4 4 5]
 [5 5 5]
 [5 4 5]
 [4 5 5]]


In [28]:
get_unique_rows(X)

array([[4, 4, 5],
       [4, 5, 5],
       [5, 4, 4],
       [5, 4, 5],
       [5, 5, 5]], dtype=int32)